In [18]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
import seaborn as sns
from csv import reader
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori, association_rules

In [19]:
data=pd.read_csv("store_data.txt",header=None)
data.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil
1,burgers,meatballs,eggs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,chutney,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,turkey,avocado,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,mineral water,milk,energy bar,whole wheat rice,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [20]:
products = []
with open('store_data.txt', 'r') as read_obj:
    csv_reader = reader(read_obj)
    for row in csv_reader:
        products.append(row)

In [21]:
items = set(sum(products, []))

In [22]:
items

{' asparagus',
 'almonds',
 'antioxydant juice',
 'asparagus',
 'avocado',
 'babies food',
 'bacon',
 'barbecue sauce',
 'black tea',
 'blueberries',
 'body spray',
 'bramble',
 'brownies',
 'bug spray',
 'burger sauce',
 'burgers',
 'butter',
 'cake',
 'candy bars',
 'carrots',
 'cauliflower',
 'cereals',
 'champagne',
 'chicken',
 'chili',
 'chocolate',
 'chocolate bread',
 'chutney',
 'cider',
 'clothes accessories',
 'cookies',
 'cooking oil',
 'corn',
 'cottage cheese',
 'cream',
 'dessert wine',
 'eggplant',
 'eggs',
 'energy bar',
 'energy drink',
 'escalope',
 'extra dark chocolate',
 'flax seed',
 'french fries',
 'french wine',
 'fresh bread',
 'fresh tuna',
 'fromage blanc',
 'frozen smoothie',
 'frozen vegetables',
 'gluten free bar',
 'grated cheese',
 'green beans',
 'green grapes',
 'green tea',
 'ground beef',
 'gums',
 'ham',
 'hand protein bar',
 'herb & pepper',
 'honey',
 'hot dogs',
 'ketchup',
 'light cream',
 'light mayo',
 'low fat yogurt',
 'magazines',
 'mashed potato',
 'mayonnaise',
 'meatballs',
 'melons',
 'milk',
 'mineral water',
 'mint',
 'mint green tea',
 'muffins',
 'mushroom cream sauce',
 'napkins',
 'nonfat milk',
 'oatmeal',
 'oil',
 'olive oil',
 'pancakes',
 'parmesan cheese',
 'pasta',
 'pepper',
 'pet food',
 'pickles',
 'protein bar',
 'red wine',
 'rice',
 'salad',
 'salmon',
 'salt',
 'sandwich',
 'shallot',
 'shampoo',
 'shrimp',
 'soda',
 'soup',
 'spaghetti',
 'sparkling water',
 'spinach',
 'strawberries',
 'strong cheese',
 'tea',
 'tomato juice',
 'tomato sauce',
 'tomatoes',
 'toothpaste',
 'turkey',
 'vegetables mix',
 'water spray',
 'white wine',
 'whole weat flour',
 'whole wheat pasta',
 'whole wheat rice',
 'yams',
 'yogurt cake',
 'zucchini'}

In [23]:
s=list(items)

In [24]:
df = pd.DataFrame(columns=s)
df

Empty DataFrame
Columns: [hand protein bar, pickles, spaghetti, almonds, energy drink, fresh bread, antioxydant juice, spinach, soda, oil, mineral water, honey, grated cheese, ham, yogurt cake, black tea, champagne, energy bar, brownies, sandwich, burgers, cottage cheese, blueberries, bramble, cream, salt, candy bars, turkey, ketchup, frozen vegetables, melons, chicken, flax seed, cooking oil, shrimp, toothpaste, cereals, shampoo, body spray, fresh tuna, tomato juice, eggs, butter, chocolate bread, escalope, mayonnaise, meatballs, barbecue sauce, chocolate, milk, tomatoes, hot dogs, mashed potato, eggplant, sparkling water, pasta, french wine, gums, fromage blanc, whole wheat pasta, strawberries, magazines, carrots, tea, gluten free bar, cauliflower, asparagus, mint green tea, pet food, cider,  asparagus, bacon, dessert wine, babies food, avocado, whole wheat rice, pepper, pancakes, bug spray, clothes accessories, shallot, protein bar, soup, oatmeal, nonfat milk, ground beef, low fat yogurt, extra dark chocolate, burger sauce, cookies, salad, green beans, red wine, white wine, chili, strong cheese, water spray, corn, light cream, herb & pepper, ...]
Index: []

[0 rows x 120 columns]

In [25]:
encoder = TransactionEncoder()
transactions = encoder.fit(products).transform(products)

In [26]:
transactions = transactions.astype('int')

In [27]:
df = pd.DataFrame(transactions, columns=encoder.columns_)

In [28]:
df.head()

,asparagus,almonds,antioxydant juice,asparagus,avocado,babies food,bacon,barbecue sauce,black tea,blueberries,...,turkey,vegetables mix,water spray,white wine,whole weat flour,whole wheat pasta,whole wheat rice,yams,yogurt cake,zucchini
0,0,1,1,0,1,0,0,0,0,0,...,0,1,0,0,1,0,0,1,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,1,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0

In [29]:
df.shape

(7501, 120)

In [30]:
frequent_itemsets = apriori(df, min_support=0.01, use_colnames=True)
frequent_itemsets.head(20)

C:\Users\HP\anaconda3\lib\site-packages\mlxtend\frequent_patterns\fpcommon.py:111: DeprecationWarning: DataFrames with non-bool types result in worse computationalperformance and their support might be discontinued in the future.Please use a DataFrame with bool type
  warnings.warn(

     support          itemsets
0   0.020397         (almonds)
1   0.033329         (avocado)
2   0.010799  (barbecue sauce)
3   0.014265       (black tea)
4   0.011465      (body spray)
5   0.033729        (brownies)
6   0.087188         (burgers)
7   0.030129          (butter)
8   0.081056            (cake)
9   0.015331         (carrots)
10  0.025730         (cereals)
11  0.046794       (champagne)
12  0.059992         (chicken)
13  0.163845       (chocolate)
14  0.010532           (cider)
15  0.080389         (cookies)
16  0.051060     (cooking oil)
17  0.031862  (cottage cheese)
18  0.013198        (eggplant)
19  0.179709            (eggs)

In [31]:
frequent_itemsets['length'] = frequent_itemsets['itemsets'].apply(lambda x: len(x))
frequent_itemsets.head()

    support          itemsets  length
0  0.020397         (almonds)       1
1  0.033329         (avocado)       1
2  0.010799  (barbecue sauce)       1
3  0.014265       (black tea)       1
4  0.011465      (body spray)       1

In [32]:
rules = association_rules(frequent_itemsets, metric="lift", min_threshold=1)
rules.head()

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(mineral water),(avocado),0.238368,0.033329,0.011598,0.048658,1.459926,0.003654,1.016113
1,(avocado),(mineral water),0.033329,0.238368,0.011598,0.348000,1.459926,0.003654,1.168147
2,(burgers),(cake),0.087188,0.081056,0.011465,0.131498,1.622319,0.004398,1.058080
3,(cake),(burgers),0.081056,0.087188,0.011465,0.141447,1.622319,0.004398,1.063198
4,(chocolate),(burgers),0.163845,0.087188,0.017064,0.104150,1.194537,0.002779,1.018933

In [33]:
rules[(rules['lift'] >= 2)]

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
188,(frozen vegetables),(shrimp),0.095321,0.071457,0.016664,0.174825,2.446574,0.009853,1.125268
189,(shrimp),(frozen vegetables),0.071457,0.095321,0.016664,0.233209,2.446574,0.009853,1.179825
192,(frozen vegetables),(tomatoes),0.095321,0.068391,0.016131,0.169231,2.474464,0.009612,1.121381
193,(tomatoes),(frozen vegetables),0.068391,0.095321,0.016131,0.235867,2.474464,0.009612,1.183930
194,(grated cheese),(ground beef),0.052393,0.098254,0.011332,0.216285,2.201294,0.006184,1.150605
195,(ground beef),(grated cheese),0.098254,0.052393,0.011332,0.115332,2.201294,0.006184,1.071145
214,(ground beef),(herb & pepper),0.098254,0.049460,0.015998,0.162822,3.291994,0.011138,1.135410
215,(herb & pepper),(ground beef),0.049460,0.098254,0.015998,0.323450,3.291994,0.011138,1.332860
220,(ground beef),(olive oil),0.098254,0.065858,0.014131,0.143826,2.183889,0.007661,1.091066
221,(olive oil),(ground beef),0.065858,0.098254,0.014131,0.214575,2.183889,0.007661,1.148100
226,(ground beef),(spaghetti),0.098254,0.174110,0.039195,0.398915,2.291162,0.022088,1.373997
227,(spaghetti),(ground beef),0.174110,0.098254,0.039195,0.225115,2.291162,0.022088,1.163716
252,(soup),(milk),0.050527,0.129583,0.015198,0.300792,2.321232,0.008651,1.244861
253,(milk),(soup),0.129583,0.050527,0.015198,0.117284,2.321232,0.008651,1.075627
290,(red wine),(spaghetti),0.028130,0.174110,0.010265,0.364929,2.095966,0.005368,1.300468
291,(spaghetti),(red wine),0.174110,0.028130,0.010265,0.058959,2.095966,0.005368,1.032761
296,(shrimp),(tomatoes),0.071457,0.068391,0.011199,0.156716,2.291481,0.006311,1.104740
297,(tomatoes),(shrimp),0.068391,0.071457,0.011199,0.163743,2.291481,0.006311,1.110355
319,"(mineral water, chocolate)",(ground beef),0.052660,0.098254,0.010932,0.207595,2.112849,0.005758,1.137987
322,(ground beef),"(mineral water, chocolate)",0.098254,0.052660,0.010932,0.111262,2.112849,0.005758,1.065939
325,"(mineral water, chocolate)",(milk),0.052660,0.129583,0.013998,0.265823,2.051375,0.007174,1.185568
328,(milk),"(mineral water, chocolate)",0.129583,0.052660,0.013998,0.108025,2.051375,0.007174,1.062070
330,"(chocolate, spaghetti)",(milk),0.039195,0.129583,0.010932,0.278912,2.152382,0.005853,1.207088
335,(milk),"(chocolate, spaghetti)",0.129583,0.039195,0.010932,0.084362,2.152382,0.005853,1.049329
343,"(mineral water, eggs)",(ground beef),0.050927,0.098254,0.010132,0.198953,2.024892,0.005128,1.125710
344,"(ground beef, eggs)",(mineral water),0.019997,0.238368,0.010132,0.506667,2.125563,0.005365,1.543848
345,(mineral water),"(ground beef, eggs)",0.238368,0.019997,0.010132,0.042506,2.125563,0.005365,1.023507
346,(ground beef),"(mineral water, eggs)",0.098254,0.050927,0.010132,0.103121,2.024892,0.005128,1.058195
364,"(mineral water, frozen vegetables)",(milk),0.035729,0.129583,0.011065,0.309701,2.389991,0.006435,1.260929
365,"(mineral water, milk)",(frozen vegetables),0.047994,0.095321,0.011065,0.230556,2.418737,0.006490,1.175757
368,(frozen vegetables),"(mineral water, milk)",0.095321,0.047994,0.011065,0.116084,2.418737,0.006490,1.077033
369,(milk),"(mineral water, frozen vegetables)",0.129583,0.035729,0.011065,0.085391,2.389991,0.006435,1.054299
371,"(mineral water, spaghetti)",(frozen vegetables),0.059725,0.095321,0.011998,0.200893,2.107549,0.006305,1.132113
374,(frozen vegetables),"(mineral water, spaghetti)",0.095321,0.059725,0.011998,0.125874,2.107549,0.006305,1.075674
376,"(mineral water, ground beef)",(milk),0.040928,0.129583,0.011065,0.270358,2.086376,0.005762,1.192938
377,"(mineral water, milk)",(ground beef),0.047994,0.098254,0.011065,0.230556,2.346536,0.006350,1.171945
378,"(ground beef, milk)",(mineral water),0.021997,0.238368,0.011065,0.503030,2.110308,0.005822,1.532552
379,(mineral water),"(ground beef, milk)",0.238368,0.021997,0.011065,0.046421,2.110308,0.005822,1.025612
380,(ground beef),"(mineral water, milk)",0.098254,0.047994,0.011065,0.112619,2.346536,0.006350,1.072827
381,(milk),"(mineral water, ground beef)",0.129583,0.040928,0.011065,0.085391,2.086376,0.005762,1.048614
382,"(mineral water, spaghetti)",(ground beef),0.059725,0.098254,0.017064,0.285714,2.907928,0.011196,1.262445
383,"(mineral water, ground beef)",(spaghetti),0.040928,0.174110,0.017064,0.416938,2.394681,0.009938,1.416470
386,(spaghetti),"(mineral water, ground beef)",0.174110,0.040928,0.017064,0.098009,2.394681,0.009938,1.063284
387,(ground beef),"(mineral water, spaghetti)",0.098254,0.059725,0.017064,0.173677,2.907928,0.011196,1.137902
388,"(mineral water, spaghetti)",(milk),0.059725,0.129583,0.015731,0.263393,2.032623,0.007992,1.181657
393,(milk),"(mineral water, spaghetti)",0.129583,0.059725,0.015731,0.121399,2.032623,0.007992,1.070195
394,"(mineral water, spaghetti)",(olive oil),0.059725,0.065858,0.010265,0.171875,2.609786,0.006332,1.128021
395,"(mineral water, olive oil)",(spaghetti),0.027596,0.174110,0.010265,0.371981,2.136468,0.005460,1.315071
398,(spaghetti),"(mineral water, olive oil)",0.174110,0.027596,0.010265,0.058959,2.136468,0.005460,1.033327
399,(olive oil),"(mineral water, spaghetti)",0.065858,0.059725,0.010265,0.155870,2.609786,0.006332,1.113898
401,"(mineral water, spaghetti)",(pancakes),0.059725,0.095054,0.011465,0.191964,2.019529,0.005788,1.119933
404,(pancakes),"(mineral water, spaghetti)",0.095054,0.059725,0.011465,0.120617,2.019529,0.005788,1.069244